### ISSUE TITLE
Getting "No rule to make target 'clean'" error.

### ISSUE THREAD

**Issue by brandonhill** [betaflight/docker-betaflight-build#2]
```
$ docker run --rm -ti -v `pwd`:/opt/betaflight betaflight/betaflight-build
Unable to find image 'betaflight/betaflight-build:latest' locally
latest: Pulling from betaflight/betaflight-build
d5c6f90da05d: Pull complete 
1300883d87d5: Pull complete 
c220aa3cfc1b: Pull complete 
2e9398f099dc: Pull complete 
dc27a084064f: Pull complete 
3f45b02343a4: Pull complete 
e4ca3691d5a5: Pull complete 
230c87c11e77: Pull complete 
5ac912f2f785: Pull complete 
49a07c48bcd4: Pull complete 
945a9f97e21b: Pull complete 
bb1f9010ede8: Pull complete 
Digest: sha256:8893fc7aebab171c08f191479d60c921e8631c4f53bd65958c8ac587612a88c0
Status: Downloaded newer image for betaflight/betaflight-build:latest
make: *** No rule to make target 'clean'.  Stop.
```

```
$ docker run -e "PLATFORM=CC3D" --rm -ti -v `pwd`:/opt/betaflight betaflight/betaflight-build
make: *** No rule to make target 'clean'.  Stop.
```

```
$ docker run -e "PLATFORM=ALL" --rm -ti -v `pwd`:/opt/betaflight betaflight/betaflight-build
make: *** No rule to make target 'clean_all'.  Stop.
```
What am I doing wrong?

**Comment by Mechotronic** [comment]
What did you do to correct this Brandon? I have the same fault.

**Comment by brandonhill** [comment]
Hi @Mechotronic,

I'm at work and not 100% sure off hand, but I think this was happening because I cloned `betaflight` to a subdirectory in my user directory, when it should be in the root of your user folder.

Hope that helps!

**Comment by vindennl48** [comment]
@Mechotronic,

I ran into the same issue.  The fix was making sure you are inside the betaflight repository directory when you run the docker command.


```
$ pwd
/home/<user name>/betaflight
$ docker run --rm -ti -v `pwd`:/opt/betaflight betaflight/betaflight-build
```

**Comment by Mechotronic** [comment]
Thanks guys. I'll try that.

**Comment by DanO83** [comment]
i'm using a windows 10 machine with powershell, i have got the same error. Anyone got an idea ?
Trying to build a custom hex for betaflightf3 with gps support (disabling dshot to make it fit)

PS C:\Users\Daniel> cd betaflight
PS C:\Users\Daniel\betaflight> docker run --rm -ti -v `pwd`:/opt/betaflight betaflight/betaflight-build
make: *** No rule to make target 'clean'.  Stop.

**Comment by djmartin** [comment]
Hi Daniel, (& anyone else finding this page looking for a fix) - On windows I found it best to make the path with double quotes 
"C:\\Users\\<username>\\betaflight"
Hope this helps :)
