### ISSUE TITLE
Compiler error on SITL target

### ISSUE THREAD

**Issue by kmitchel** [betaflight/docker-betaflight-build#8]
I was trying to build all targets for https://github.com/betaflight/betaflight/pull/6355 with D:\github\betaflight>docker run -e "PLATFORM=ALL" --rm -it -v "//d/github/betaflight":/opt/betaflight betaflight/betaflight-build

Build failed with

Building SIRINFPV succeeded.
Building SITL
make[1]: Entering directory '/opt/betaflight'
make -j ./obj/betaflight_3.5.0_SITL.bin
make[2]: Entering directory '/opt/betaflight'
%% dyad.c
%% (speed optimised) accgyro_fake.c
%% (size optimised) barometer_fake.c
ccache: error: Could not find compiler "gcc" in PATH
ccache: error: Could not find compiler "gcc" in PATH
ccache: error: Could not find compiler "gcc" in PATH
Makefile:305: recipe for target 'obj/main/SITL/drivers/accgyro/accgyro_fake.o' failed
make[2]: *** [obj/main/SITL/drivers/accgyro/accgyro_fake.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:305: recipe for target 'obj/main/SITL/drivers/barometer/barometer_fake.o' failed
make[2]: *** [obj/main/SITL/drivers/barometer/barometer_fake.o] Error 1
Makefile:305: recipe for target 'obj/main/SITL/./lib/main/dyad/dyad.o' failed
make[2]: *** [obj/main/SITL/./lib/main/dyad/dyad.o] Error 1
%% (size optimised) compass_fake.c
%% (size optimised) serial_tcp.c
ccache: error: Could not find compiler "gcc" in PATH
ccache: error: Could not find compiler "gcc" in PATH
Makefile:305: recipe for target 'obj/main/SITL/drivers/compass/compass_fake.o' failed
make[2]: *** [obj/main/SITL/drivers/compass/compass_fake.o] Error 1
Makefile:305: recipe for target 'obj/main/SITL/drivers/serial_tcp.o' failed
make[2]: *** [obj/main/SITL/drivers/serial_tcp.o] Error 1
make[2]: Leaving directory '/opt/betaflight'
Makefile:412: recipe for target 'binary' failed
make[1]: *** [binary] Error 2
make[1]: Leaving directory '/opt/betaflight'
Makefile:356: recipe for target 'SITL' failed
make: *** [SITL] Error 2

Same error when trying to build just SITL target.
Same error when trying to build upstream/master.
Target builds on my xubuntu vm.

**Comment by mikeller** [comment]
@kmitchel: Building SITL in the docker VM is not supported - since the SITL target needs a linux environment to run in anyway, the best approach is to build it on the machine it will be run on.

**Comment by kmitchel** [comment]
Would it be acceptable to move SITL into UNSUPPORTED_TARGETS, so it's not caught up in ALL?

**Comment by mikeller** [comment]
Not really, as `UNSUPPORTED_TARGETS` isn't specific to the docker build.

The docker build environment was created to give users not running linux a way (amongst others) to build individual targets, and specifically to allow them to do so without having to install a lot of different tools.

From the sound of it, what you are trying to do is different from this, so there might be a better way for you to get there. Can you please describe what you are trying to do?

**Comment by kmitchel** [comment]
Out of curiosity, I was trying to compare compile times between the docker container, and a XUbuntu-Core 18.04 VM.   I have no real need of the SITL target, just noticed that it killed off the docker build.

I played with adding a docker-all target
in dockerfile
41:make ARM_SDK_DIR=${ARM_SDK_DIR} all_docker ${EXTRA_OPTIONS}; \

in Makefile
331:all_docker: $(DOCKER_TARGETS)

in targets.mk
DOCKER_TARGETS  := $(filter-out $(SITL_TARGETS), $(VALID_TARGETS))

It doesn't work.  if I replace $(SITL_TARGETS) with SITL it works...like $(SITL_TARGETS) isn't populated.

**Comment by mikeller** [comment]
@kmitchel:

Ah, interesting. What were your findings?

The one thing that I think might be of interest for users would be to compare these build times to the build times of builds done in WSL (https://github.com/betaflight/betaflight/wiki/Building-Betaflight-on-Windows,-the-Linux-subsystem-way).

It would probably be relatively easy to add gcc and any other tools / libraries required to build SITL to the list of packages that is installed through the Dockerfile - if you do so please open a pull request to add this to the official Dockerfile.

**Comment by kmitchel** [comment]
dockerfile 17:RUN DEBIAN_FRONTEND=noninteractive apt-get -y install gcc

Kind of surprised it was that simple.  SITL compiles with a warninlib/main/dyad/dyad.c: In function 'dyad_update':
lib/main/dyad/dyad.c:738:12: warning: this statement may fall through [-Wimplicit-fallthrough=]
         if (select_has(&dyad_selectSet, SELECT_READ, stream->sockfd)) {
            ^
lib/main/dyad/dyad.c:746:7: note: here
       case DYAD_STATE_CLOSING:
       ^~~~g

I'll continue to test tomorrow, TY.

**Comment by mikeller** [comment]
I assumed it would be - SITL is a native linux build. The warning is probably just a `switch` statement that needs an explicit `FALLTHROUGH` - these warnings got added to `gcc` after the SITL target was introduced.
